# Generated by Django 3.1.6 on 2021-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deviraldigim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviraldim', models.IntegerField(db_column='DevirAldim')),
            ],
            options={
                'db_table': 'DevirAldigim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disiplin',
            fields=[
                ('disiplin_id', models.AutoField(db_column='Disiplin_id', primary_key=True, serialize=False)),
                ('adisoyadi', models.CharField(db_column='AdiSoyadi', max_length=50)),
                ('ehliyetno', models.IntegerField(db_column='EhliyetNo')),
                ('tarih', models.DateField(db_column='Tarih')),
                ('uyarisayisi', models.IntegerField(db_column='UyariSayisi')),
                ('uyariraporu', models.CharField(db_column='UyariRaporu', max_length=100)),
                ('mecliskarari', models.CharField(db_column='MeclisKarari', max_length=1000)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=1000)),
            ],
            options={
                'db_table': 'Disiplin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etkinliksurus',
            fields=[
                ('etkinlik_id', models.AutoField(db_column='Etkinlik_Id', primary_key=True, serialize=False)),
                ('etkinlikadi', models.CharField(db_column='EtkinlikAdi', max_length=50)),
                ('etkinliktarihi', models.DateField(db_column='EtkinlikTarihi')),
                ('etkinlikkatilim', models.IntegerField(db_column='EtkinlikKatilim')),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=500)),
                ('etkinlikyapildimi', models.CharField(db_column='EtkinlikYapildiMi', max_length=75)),
            ],
            options={
                'db_table': 'EtkinlikSurus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giris',
            fields=[
                ('kullanici_id', models.AutoField(db_column='Kullanici_id', primary_key=True, serialize=False)),
                ('ehliyetno', models.IntegerField(db_column='EhliyetNo')),
                ('sifre', models.CharField(db_column='Sifre', max_length=10)),
                ('yetki', models.IntegerField(db_column='Yetki')),
                ('gorevi', models.CharField(db_column='Gorevi', max_length=10)),
            ],
            options={
                'db_table': 'Giris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Girislog',
            fields=[
                ('log_id', models.AutoField(db_column='Log_id', primary_key=True, serialize=False)),
                ('tarih', models.CharField(db_column='Tarih', max_length=50)),
                ('ehliyetno', models.CharField(db_column='EhliyetNo', max_length=20)),
                ('derece', models.CharField(blank=True, db_column='Derece', max_length=75, null=True)),
            ],
            options={
                'db_table': 'GirisLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Harcamalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harcamatarih', models.DateField(db_column='HarcamaTarih')),
                ('nedenharcandi', models.CharField(db_column='NedenHarcandi', max_length=50)),
                ('harcananyer', models.CharField(db_column='HarcananYer', max_length=50)),
                ('harcamayapan', models.CharField(db_column='HarcamaYapan', max_length=50)),
                ('harcanantutar', models.CharField(db_column='HarcananTutar', max_length=11)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=250)),
            ],
            options={
                'db_table': 'Harcamalar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehliyetno', models.IntegerField(db_column='EhliyetNo')),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kasaborc',
            fields=[
                ('kasaborc_id', models.AutoField(db_column='KasaBorc_id', primary_key=True, serialize=False)),
                ('borctarihi', models.DateField(db_column='BorcTarihi')),
                ('adisoyadi', models.CharField(db_column='AdiSoyadi', max_length=25)),
                ('ehliyetno', models.IntegerField(db_column='EhliyetNo')),
                ('alinantutar', models.IntegerField(db_column='AlinanTutar')),
                ('alinmasebebi', models.CharField(db_column='AlinmaSebebi', max_length=100)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=1000)),
            ],
            options={
                'db_table': 'KasaBorc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kmtakip',
            fields=[
                ('km_id', models.AutoField(db_column='Km_id', primary_key=True, serialize=False)),
                ('adisoyadi', models.CharField(db_column='AdiSoyadi', max_length=25)),
                ('ehliyetno', models.CharField(db_column='EhliyetNo', max_length=10)),
                ('tarih', models.DateField(db_column='Tarih')),
                ('rotaturu', models.CharField(db_column='RotaTuru', max_length=20)),
                ('km', models.DecimalField(db_column='KM', decimal_places=1, max_digits=5)),
                ('rota', models.CharField(db_column='Rota', max_length=250)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=250)),
            ],
            options={
                'db_table': 'KmTakip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kunye',
            fields=[
                ('kunye_id', models.AutoField(db_column='Kunye_id', primary_key=True, serialize=False)),
                ('nick', models.CharField(db_column='Nick', max_length=15)),
                ('adisoyadi', models.CharField(db_column='AdiSoyadi', max_length=30)),
                ('dogumtarihi', models.DateField(db_column='DogumTarihi')),
                ('pozisyon', models.CharField(db_column='Pozisyon', max_length=15)),
                ('basvurutarihi', models.DateField(db_column='BasvuruTarihi')),
                ('kgiristarihi', models.DateField(db_column='KGirisTarihi')),
                ('meslegi', models.CharField(db_column='Meslegi', max_length=50)),
                ('yemintarihi', models.DateField(db_column='YeminTarihi')),
                ('ehliyetno', models.CharField(blank=True, db_column='EhliyetNo', max_length=10, null=True)),
                ('kangrubu', models.CharField(db_column='KanGrubu', max_length=5)),
                ('motormarka', models.CharField(db_column='MotorMarka', max_length=25)),
                ('motorcc', models.CharField(db_column='MotorCC', max_length=5)),
                ('plaka', models.CharField(db_column='Plaka', max_length=10)),
                ('telno', models.CharField(db_column='TelNo', max_length=15)),
                ('yakintelno', models.CharField(db_column='YakinTelNo', max_length=15)),
                ('yelekdontarihi', models.CharField(db_column='YelekDonTarihi', max_length=11)),
            ],
            options={
                'db_table': 'Kunye',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meclis',
            fields=[
                ('meclis_id', models.AutoField(db_column='Meclis_id', primary_key=True, serialize=False)),
                ('tarih', models.DateField(db_column='Tarih')),
                ('konu', models.CharField(db_column='Konu', max_length=100)),
                ('alinankarar', models.CharField(db_column='AlinanKarar', max_length=800)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=250)),
            ],
            options={
                'db_table': 'Meclis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pachyelek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehliyetno', models.IntegerField(db_column='EhliyetNo')),
                ('adisoyadi', models.CharField(db_column='AdiSoyadi', max_length=25)),
                ('verilmetarihi', models.DateField(db_column='VerilmeTarihi')),
                ('yelek', models.CharField(db_column='Yelek', max_length=5)),
                ('bayrak', models.CharField(db_column='Bayrak', max_length=5)),
                ('onsancak', models.CharField(db_column='OnSancak', max_length=5)),
                ('onkurukafa', models.CharField(db_column='OnKuruKafa', max_length=5)),
                ('chopper', models.CharField(db_column='Chopper', max_length=5)),
                ('mk', models.CharField(db_column='Mk', max_length=5)),
                ('bursa', models.CharField(db_column='Bursa', max_length=5)),
                ('sirtsancak', models.CharField(db_column='SirtSancak', max_length=5)),
                ('sirtkurukafa', models.CharField(db_column='SirtKuruKafa', max_length=5)),
                ('turkiye', models.CharField(db_column='Turkiye', max_length=5)),
            ],
            options={
                'db_table': 'PachYelek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sayman',
            fields=[
                ('sayman_id', models.AutoField(db_column='Sayman_id', primary_key=True, serialize=False)),
                ('adisoyadi', models.CharField(db_column='AdiSoyadi', max_length=30)),
                ('ehliyetno', models.IntegerField(db_column='EhliyetNo')),
                ('odemetarihi', models.DateField(db_column='OdemeTarihi')),
                ('odemesekli', models.CharField(db_column='OdemeSekli', max_length=25)),
                ('odenentl', models.DecimalField(db_column='OdenenTl', decimal_places=1, max_digits=5)),
                ('odemeaciklama', models.CharField(db_column='OdemeAciklama', max_length=30)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=250)),
            ],
            options={
                'db_table': 'Sayman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('stok_id', models.AutoField(db_column='Stok_id', primary_key=True, serialize=False)),
                ('yeleksayisi', models.IntegerField(db_column='YelekSayisi')),
                ('fullpachsayisi', models.IntegerField(db_column='FullPachSayisi')),
                ('bayrak', models.IntegerField(db_column='Bayrak')),
                ('onsancak', models.IntegerField(db_column='OnSancak')),
                ('onkurukafa', models.IntegerField(db_column='OnKuruKafa')),
                ('chopper', models.IntegerField(db_column='Chopper')),
                ('mk', models.IntegerField(db_column='MK')),
                ('bursa', models.IntegerField(db_column='Bursa')),
                ('sirtsancak', models.IntegerField(db_column='SirtSancak')),
                ('sirtkurukafa', models.IntegerField(db_column='SirtKuruKafa')),
                ('turkiye', models.IntegerField(db_column='Turkiye')),
                ('stoktarihi', models.DateField(auto_now=True, db_column='StokTarihi')),
            ],
            options={
                'db_table': 'Stok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surushatirlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(db_column='Tarih')),
                ('surusadi', models.CharField(db_column='SurusAdi', max_length=100)),
                ('rota', models.CharField(db_column='Rota', max_length=1000)),
                ('ortkm', models.IntegerField(db_column='OrtKm')),
                ('yapildimi', models.CharField(db_column='YapildiMi', max_length=5)),
                ('aciklama', models.CharField(db_column='Aciklama', max_length=5000)),
            ],
            options={
                'db_table': 'SurusHatirlat',
                'managed': False,
            },
        ),
    ]
