# Generated by Django 3.1.6 on 2021-02-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sancakRestDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviraldigim',
            options={'verbose_name_plural': 'Devranilan'},
        ),
        migrations.AlterModelOptions(
            name='disiplin',
            options={'verbose_name_plural': 'Disiplin Cezalari'},
        ),
        migrations.AlterModelOptions(
            name='etkinliksurus',
            options={'verbose_name_plural': 'Surus Etkinlikleri'},
        ),
        migrations.AlterModelOptions(
            name='giris',
            options={'verbose_name_plural': 'Giris Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='girislog',
            options={'verbose_name_plural': 'Giris Kayitlari'},
        ),
        migrations.AlterModelOptions(
            name='harcamalar',
            options={'verbose_name_plural': 'Harcamalar'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Ehliyet Fotograflari'},
        ),
        migrations.AlterModelOptions(
            name='kasaborc',
            options={'verbose_name_plural': 'Karizma Takibi'},
        ),
        migrations.AlterModelOptions(
            name='kmtakip',
            options={'verbose_name_plural': 'Kilometre Takibi'},
        ),
        migrations.AlterModelOptions(
            name='kunye',
            options={'verbose_name_plural': 'Kunye'},
        ),
        migrations.AlterModelOptions(
            name='meclis',
            options={'verbose_name_plural': 'Meclis Kararlari'},
        ),
        migrations.AlterModelOptions(
            name='pachyelek',
            options={'verbose_name_plural': 'Pach ve Yelek Takibi'},
        ),
        migrations.AlterModelOptions(
            name='sayman',
            options={'verbose_name_plural': 'Odemeler(Sayman)'},
        ),
        migrations.AlterModelOptions(
            name='stok',
            options={'verbose_name_plural': 'Stok'},
        ),
        migrations.AlterModelOptions(
            name='surushatirlat',
            options={'verbose_name_plural': 'Planlanan Surusler'},
        ),
    ]
