# Generated by Django 3.1.6 on 2021-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancakRestDB', '0003_auto_20210208_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Web Giriş Kayıtları',
                'db_table': 'MemberLogs',
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.BinaryField(editable=True),
        ),
    ]
